# Docker Compose version - specifies the schema version
version: "3.8"

# Services section - defines all the containers that make up your application
services:
  # Backend service configuration
  backend:
    # Build the Docker image from the ./backend directory using its Dockerfile
    build: ./backend
    # Map host port 3001 to container port 3001
    ports:
      - "3001:3001"
    # Load environment variables from the backend .env file (should contain cloud DB URLs)
    env_file:
      - ./backend/.env

  # Frontend service configuration
  frontend:
    # Build the Docker image from the ./frontend directory using its Dockerfile
    build: ./frontend
    # Map host port 3000 to container port 3000
    ports:
      - "3000:3000"
    # Load environment variables from the frontend .env file
    env_file:
      - ./frontend/.env